name: My First Workflows

on: push

jobs:
  first-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: print and read
        run: |
          echo "Hello First Workflow Run"
          ls -ltrah
          cat README.md 
          
