name: My First Workflows

on: push

jobs:
  first-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: add permission
        run: chmod +x printandread.sh

      - name: print and read
        run: ./printandread.sh

          
